import {
  loginPath,
  signUpPath,
  mePath,
  questionnairePath,
  questionnaireDetailsPath,
  questionnaireDataPath,
  questionnaireDataDetailsPath,
  questionPath,
  questionDetailsPath,
  answerOptionPath,
  answerOptionDetailsPath,
  answerPath,
  answerDetailsPath,
  applierPath,
  applierDetailsPath,
  devicePath,
  deviceDetailsPath,
} from './paths/';
export default {
  '/login': loginPath,
  '/signup': signUpPath,
  '/me': mePath,
  '/questionnaires': questionnairePath,
  '/questionnaires/{id}': questionnaireDetailsPath,
  '/questionnaires/questionnaire_data': questionnaireDataPath,
  '/questionnaires/questionnaire_data/{id}': questionnaireDataDetailsPath,
  '/questions': questionPath,
  '/questions/{id}': questionDetailsPath,
  '/questions/answer_option': answerOptionPath,
  '/questions/answer_option/{id}': answerOptionDetailsPath,
  '/data/answer': answerPath,
  '/data/answer/{id}': answerDetailsPath,
  '/appliers': applierPath,
  '/appliers/{id}': applierDetailsPath,
  '/devices': devicePath,
  '/devices/{id}': deviceDetailsPath,
};
