import {
  accessTokenSchema,
  accountSchema,
  answerCreationSchema,
  answerOptionParamsSchema,
  answerOptionSchema,
  answerParamsSchema,
  answerSchema,
  applierParamsSchema,
  applierSchema,
  audioUploadSchema,
  deviceParamsSchema,
  deviceSchema,
  errorSchema,
  healthCheckSchema,
  loginParamsSchema,
  questionCreationSchema,
  questionnaireCreationSchema,
  questionnaireDataParamsSchema,
  questionnaireDataPostSchema,
  questionnaireDataSchema,
  questionnaireDataMultipleParamsSchema,
  questionnaireParamsSchema,
  questionnaireSchema,
  questionParamsSchema,
  questionSchema,
  reportsQuestionnaireDataSchema,
  signUpParamsSchema,
} from './schemas/';

export default {
  signUpParams: signUpParamsSchema,
  loginParams: loginParamsSchema,
  questionnaireParams: questionnaireParamsSchema,
  questionnaireDataParams: questionnaireDataParamsSchema,
  questionnaireDataMultipleParams: questionnaireDataMultipleParamsSchema,
  questionParams: questionParamsSchema,
  answerOptionParams: answerOptionParamsSchema,
  answerParams: answerParamsSchema,
  applierParams: applierParamsSchema,
  deviceParams: deviceParamsSchema,

  questionnaire: questionnaireSchema,
  questionnaireCreation: questionnaireCreationSchema,
  questionnaireData: questionnaireDataSchema,
  questionnaireDataCreation: questionnaireDataPostSchema,
  question: questionSchema,
  questionCreation: questionCreationSchema,
  answerOption: answerOptionSchema,
  answer: answerSchema,
  answerCreation: answerCreationSchema,
  applier: applierSchema,
  device: deviceSchema,
  reportsQuestionnaireData: reportsQuestionnaireDataSchema,
  account: accountSchema,
  accessToken: accessTokenSchema,
  audioUpload: audioUploadSchema,
  healthCheck: healthCheckSchema,
  error: errorSchema,
};
